# The URL the site will be built for
title = "Home"
base_url = "https://correial.github.io/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
minify_html = true
generate_feeds = true
taxonomies = [{ name = "tags", feed = true }]

feed_filenames = ["rss.xml", "atom.xml"]
build_search_index = true
author = "Daria Kot"
# default_language = "en"


theme = "duckquill"


[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
	{ theme = "solarized-dark", filename = "syntax-theme-dark.css" },
	{ theme = "solarized-light", filename = "syntax-theme-light.css" }
]
smart_punctuation = true
bottom_footnotes = true

[search]
# index_format = "elasticlunr_json"
index_format = "fuse_json"


ignored_content = ["themes/duckquill/content/blog/the-quill-of-duck/index.ar.md"]



[extra]
# Put all your custom variables here
favicon = "/favicon.png"
accent_color = "#ff7800"
# accent_color = "#7b98e0"
accent_color_dark = "#ffa348"
fix_contrast_dark = true
bundled_fonts = true
projects_sort_by = "weight"


show_copy_button = true
show_reading_time = true
show_share_button = true
show_backlinks = true



[extra.nav]
show_feed = false
show_theme_switcher = true
links = [ 
	#{name = "Projects", 
	#menu = [
	#{url = "@/projects/project1/index.md", name = "Project #1"},
	#{url = "@/projects/project2/index.md", name = "Project #2"},
	#{url = "@/projects/index.md", name = "Project #3"} 
	#]},
	{url = "@/projects/_index.md", name = "Portfolio"},
	{url = "@/contact/index.md", name = "Contact"},
	{url = "@/resume/index.md", name = "Resume"}
]

[extra.footer]



# socials = [
# 	{ url = "https://www.linkedin.com/in/daria-kot-7a8518253/", name = "LinkedIn", icon = "%3Csvg role='img' viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg'%3E%3Ctitle%3EGitHub%3C/title%3E%3Cpath d='M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12'/%3E%3C/svg%3E" }]
show_copyright = false
show_powered_by = true
show_source = true

[extra.debug]
# Display outlines around all elements for debugging purposes
layout = false
# Don't load any styles for debugging purposes
no_styles = false